# Generated by Django 5.0.7 on 2024-10-01 17:57

import django.core.validators
import payment_term.enums
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTermTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_system', models.BooleanField(default=True)),
                ('primary_priority', models.CharField(choices=[('P', 'Preferred'), ('F', 'Flex'), ('S', 'Superflex'), ('C', 'Credit'), ('T', 'Token')], default=payment_term.enums.Priority['FIRM'], max_length=1)),
                ('primary_start', models.CharField(choices=[], default=payment_term.enums.StartDate['DELIVERY_FINISH'], max_length=1)),
                ('primary_period', models.CharField(choices=[], default=payment_term.enums.Period['MONTH'], max_length=1)),
                ('primary_offset', models.IntegerField(default=1)),
                ('primary_adjustment', models.CharField(choices=payment_term.enums.PrimaryAdjustment.all_choices, default=payment_term.enums.PrimaryAdjustment['NONE'], max_length=1)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('0.5'))])),
                ('interest_priority', models.CharField(choices=[('R', 'Firm'), ('P', 'Preferred'), ('F', 'Flex'), ('S', 'Superflex'), ('C', 'Credit'), ('T', 'Token'), ('A', 'Same as primary'), ('N', 'Not applicable')], default=payment_term.enums.Priority['NA'], max_length=1)),
                ('interest_start', models.CharField(choices=[], default=payment_term.enums.StartDate['NA'], max_length=1)),
                ('interest_period', models.CharField(choices=[('Y', 'Year'), ('Q', 'Quarter'), ('M', 'Month'), ('A', 'Same as primary'), ('N', 'Not applicable')], default=payment_term.enums.Period['NA'], max_length=1)),
                ('residue_priority', models.CharField(choices=[('P', 'Preferred'), ('F', 'Flex'), ('S', 'Superflex'), ('C', 'Credit'), ('N', 'Not applicable')], max_length=1)),
                ('residue_period', models.CharField(choices=[('Y', 'Year'), ('Q', 'Quarter'), ('M', 'Month'), ('A', 'Same as primary'), ('N', 'Not applicable')], default=payment_term.enums.Period['MONTH'], max_length=1)),
                ('token_redemption', models.CharField(choices=payment_term.enums.TokenRedemption.all_choices, default=payment_term.enums.TokenRedemption['NO'], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('templates', models.ManyToManyField(related_name='payment_terms', to='payment_term.paymenttermtemplate', verbose_name='Templates')),
            ],
            options={
                'verbose_name': 'Payment term',
                'verbose_name_plural': 'Payment terms',
            },
        ),
    ]
