# Generated by Django 5.0.7 on 2024-10-01 18:04

import payment_term.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_term', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttermtemplate',
            name='interest_start',
            field=models.CharField(choices=[('O', 'Order confirmation date'), ('S', 'Delivery start date'), ('M', 'Delivery middle date'), ('F', 'Delivery finish date'), ('D', 'Intial due date'), ('N', 'Not applicable')], default=payment_term.enums.StartDate['NA'], max_length=1),
        ),
        migrations.AlterField(
            model_name='paymenttermtemplate',
            name='primary_adjustment',
            field=models.CharField(choices=payment_term.enums.PrimaryAdjustment.all_choices, default=payment_term.enums.PrimaryAdjustment['EOP'], max_length=1),
        ),
        migrations.AlterField(
            model_name='paymenttermtemplate',
            name='primary_priority',
            field=models.CharField(choices=[('P', 'Preferred'), ('F', 'Flex'), ('S', 'Superflex'), ('C', 'Credit'), ('T', 'Token')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paymenttermtemplate',
            name='primary_start',
            field=models.CharField(choices=[('O', 'Order confirmation date'), ('S', 'Delivery start date'), ('M', 'Delivery middle date'), ('F', 'Delivery finish date'), ('N', 'Not applicable')], default=payment_term.enums.StartDate['DELIVERY_FINISH'], max_length=1),
        ),
    ]
